name: Publish npm
on:
  push:
    branches:
      - master
jobs:
  release:
    name: 🚀 Publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: 🚀 Publish
        run: npm publish --acess public
        working-directory: ./gatsby-source-strapi-plugin-navigation
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
